### ISSUE TITLE
Converted weights download for Europe

### ISSUE THREAD

**Issue by ricardorei** [bojone/labse#1]
I tried to download the converted weights in Europe but the website takes too long to load and when I was able to open the site it was all in Chinese.

It would be nice to have a more accessible way to download those weights in Europe.

Thanks!

**Comment by bojone** [comment]
Sorry for non-Chinese user. I have added a link of Google Drive ([https://drive.google.com/file/d/14Zaq8RE9NMyJb_9B-lkgFZQ9H1K-U-Nf](https://drive.google.com/file/d/14Zaq8RE9NMyJb_9B-lkgFZQ9H1K-U-Nf)). Please try it.

**Comment by ricardorei** [comment]
It works! Thank you!

**Comment by ricardorei** [comment]
When I download the zip I get a file named: _bert_model.ckpt.data-00000-of-00001_ 
Shouldn't this be just: _bert_model.ckpt_

When I try to load that checkpoint I get a: _tensorflow.python.framework.errors_impl.DataLossError_

Am I doing something wrong?
